### ISSUE TITLE
Code doesn't match paper

### ISSUE THREAD

**Issue by wangzeyu135798** [jwzhanggy/Graph-Bert#14]
Hi:
   In script_3_fine_tuning, you have one downstream task graph-clustering
   In MethodGraphBertGraphClustering,py,from line 38 to line 41, is your clustering process while you didn't reuse any pre-train results in this downstream task. Is it belong to fine-tuning?
kmeans = KMeans(n_clusters=self.cluster_number, max_iter=self.max_epoch)
if self.use_raw_feature:
       clustering_result = kmeans.fit_predict(self.data['X'])
 else:
       clustering_result = kmeans.fit_predict(sequence_output.tolist())

**Comment by jwzhanggy** [comment]
I need to make sure people can download the code and run it to get scores for all the tasks directly. A pre-trained Graph-Bert takes several Gs space, I cannot put it in github. If I put pre-trained model loading code there, you will also comment that you cannot run it since I cannot provide the pre-trained model for you to download. You can load your pre-trained model for your downstream tasks by yourself. It is very easy, you should be able to do it. Please read the READ.me descriptions before commenting on this:

"
How save/load pre-trained graph-bert?

Please refer to the attached page for model save/load in pytorch:
https://pytorch.org/tutorials/beginner/saving_loading_models.html

You can load the pre-trained graph-bert component with pytorch model (e.g., the graph-bert inside MethodGraphBertNodeClassification) with the save and load functions in the above page. According to our experiments, Save/Load Entire Model in the above page works perfectly, whereas Save/Load state_dict doesn't really work.
"
