### ISSUE TITLE
About mini-batch size

### ISSUE THREAD

**Issue by dproxy8** [jwzhanggy/Graph-Bert#5]
Hi, thank you for your work.
I have a question about mini-batch size, where can I find it in your code? 
Thank you.

**Comment by jwzhanggy** [comment]
This version of code doesn't include mini-batch size. It can be done easily by yourself depending on your application needs. Instead of feeding the complete graph, you can divide the nodes into subsets, and feed them sequentially as the mini-batches. It will also require the pre-computing of the graph-residual terms in advance if you choose to use "graph-raw residual term". Hope it will be helpful for you.
